// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://agbpmgwyfhqckdlqrkgd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFnYnBtZ3d5ZmhxY2tkbHFya2dkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3NTg2ODgsImV4cCI6MjA2OTMzNDY4OH0.3jbKDXZI5zEYHNT3rMUeoYicx41gt8T3-QctssOpsN4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});